version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pastel_cloud
    networks:
      - webnet
  web:
    build: .
    volumes:
      - static_files:/opt/static
    depends_on:
      - db
    networks:
      - webnet
  nginx:
    build: ./nginx_image
    volumes:
      - static_files:/var/www/pastel_static
    depends_on:
      - web
    ports:
     - "80:80"
    networks:
      - webnet

volumes:
  pg_data: {}
  pg_backups: {}
  static_files: {}
networks:
  webnet:
